### PR TITLE
Dependency Installer Cleanup

### PR DESCRIPTION
**Pull request by sroberts**
Still a WIP but I'm trying to improve the dependency setup, make it a bit more clean. I think it could go a long way to making CRITs deploy a bit simpler.

### CODE REVIEW

**Comment by sroberts** [comment]
So I think this works. I did the following:
- Compressed all the dependency print statements and then individual ```apt-get``` statements into a single line multi package ```apt-get install``. No one really reads that stuff anyway.
- I deleted all the individual python packages and just replaced it with the ```requirements.txt``` file. It's a cleaner installation and I assume people who need to deal with airgaps have their own way to deal with them.
- I automated a few additional steps on the way towards making a full unattended install script. That's going to be a lot harder, so I figured I'd save it for a second PR after this one.
- I cleaned up some of the CentOS stuff, but I don't know CentOS/RPM that well, so it might need some love.
- I added a place for an eventual homebrew based installation for Macs. :apple: needs some :heart: too. 

Hope this helps! Trying to keep this incremental. 

murica - imgur
_gif for basic enjoyment, not really content_

**Comment by mgoffin** [comment]
Couple things of note just looking at the install script:

* I would leave out the downloading of the code base. Some people want to run release tarballs, others might wish to use the code base as you have put it in the script using git clone. Forcing them to clone the repo to the directory they are currently in (which would be the crits_dependencies repo/folder) doesn't seem like the best idea.
* I would refrain from executing MongoDB automagically. Creating a /data/db directory is probably fine, but a couple reasons not to actually start MongoDB:
  * Not all systems require NUMA.
  * Not all systems will be running MongoDB locally.
  * Clustered systems do not run MongoDB the way that script starts it.
* Can we download MongoDB during script execution instead of keeping it with the repo?
  * Can we do the same for those RPMs?

**Comment by sroberts** [comment]
@mgoffin To your points:

1. :+1:
2. :+1:
3. :+1: for the first part. I don't know enough about RPMs, but I can try figuring it out.

I also realize I need to update the README for all this.

**Comment by dsnellgrove** [comment]
If it's acceptable I'd recommend against all the == in the requirements.txt. It can block a lot of important security updates unless you want to keep 100% on top of updates from all the projects and update this file every time. If you're concerned about major versions use the less-then syntax.

Some time ago I updated the dependencies for the project at https://github.com/crits/crits/blob/master/DEPENDENCIES and it actually secretly includes pip-like syntax in the "Required Python Libraries" section if you remove the extraneous lines and installs all the actually required packages, which wound up being a LOT less than what was in this repository. It was compiled for 3.1 so might have to be run through the UPDATES file for any changes, but here's the condensed pip requirements list:

```
ushlex
pillow
PyYAML
django<1.7
pymongo==2.7.2
python-magic
pydeep
M2Crypto
lxml
python-dateutil
cybox==2.1.0.5
stix==1.1.1.0
mongoengine==0.8.7
django-tastypie==0.11.0
django-tastypie-mongoengine==0.4.5
```

**Comment by mgoffin** [comment]
I guess going along with that thought process, we should probably make them minimum requirements, but make explicit the versions for major stuff like Django, pymongo, MongoEngine. We should probably make CybOX and STIX explicit as well given the extremely likelihood of those not being compatible with code as they role out new releases (STIX more than CybOX).

**Comment by dsnellgrove** [comment]
Yep, the snippet I included locked in the big stuff and let the little stuff float. django is an example where "django<1.7" translates into "latest 1.6.x release"

**Pull request merged**
